36 create new project button on the projects page
CodecoolArchive2023/el-proyecte-grande-sprint-1-java-tuszmak pull request #41
Opened 2023-05-09 15:51 UTC by MateWagner

2023-05-09 20:53 UTC, tuszmak requested changes

2023-05-09 20:53 UTC, tuszmak commented on src/frontend/src/pages/projects/NewProjectDrawer.js
> +    console.log(form);
remove this console log

2023-05-09 20:53 UTC, tuszmak commented on src/frontend/src/pages/projects/ProjectList.js
Should we display question description as well? It shouldn't be the whole description, but like a 50 letter version. We already have the data for it, if we want to.

2023-05-10 06:20 UTC, gerigol commented on src/frontend/src/pages/projects/NewProjectDrawer.js
> +    if (result.status === 400) {
Checking if the response was succefull is more flxible with the result.ok property ( https://developer.mozilla.org/en-US/docs/Web/API/Response/ok ) -> if (!result.ok)

2023-05-10 06:25 UTC, gerigol commented on src/frontend/src/pages/projects/NewProjectDrawer.js
> +      message.error("Problem with the Server", ERROR_MSG_DURATION);
The error message should be provided dinamically:  const errorMessage = await error.message;
message.error(errorMessage, ERROR_MSG_DURATION);

2023-05-10 06:30 UTC, MateWagner commented on src/frontend/src/pages/projects/NewProjectDrawer.js
> +    if (result.status === 400) {
This is a special case to give an error to the form field the rest is catch under

2023-05-10 06:36 UTC, MateWagner commented on src/frontend/src/pages/projects/NewProjectDrawer.js
> +      message.error("Problem with the Server", ERROR_MSG_DURATION);
i don't think await need it's a antd component https://ant.design/components/message

2023-05-10 11:28 UTC, merged