Security implementation frontend Backend
CodecoolArchive2023/el-proyecte-grande-sprint-1-java-tuszmak pull request #59
Opened 2023-05-22 12:39 UTC by MateWagner

2023-05-22 13:02 UTC, tuszmak requested changes

2023-05-22 13:02 UTC, tuszmak commented on src/frontend/src/api/upFetch.js
> +const upFetch = async (url, option) => {
Write some documentation, on when to use this hook

2023-05-22 13:02 UTC, tuszmak commented on src/frontend/src/hook/useDownFetch.js
> +const useDownFetch = (url) => {
Write some documentation for when to use this hook

2023-05-22 13:02 UTC, tuszmak commented on src/frontend/src/pages/projects/ProjectList.js
> +  };
Máté said it will be in a future pull request, so it's not done yet

2023-05-22 13:02 UTC, tuszmak commented on src/main/java/com/codecool/ecosampler/security/JWTService.java
> +    private Key getSigInKey() {
Fix typo: It's getSignInKey

2023-05-22 13:02 UTC, tuszmak commented on src/main/java/com/codecool/ecosampler/service/UserService.java
> +        return userRepository.findByEmail(email).orElseThrow(() -> new NotFoundException("No user fund on email"));
fix typo: "fund" to found

2023-05-22 14:26 UTC, MateWagner commented on src/frontend/src/api/upFetch.js
> +const upFetch = async (url, option) => {
Not a Hook :D

2023-05-22 14:41 UTC, MateWagner commented on src/frontend/src/hook/useDownFetch.js
> +const useDownFetch = (url) => {
Look above there is one

2023-05-22 15:30 UTC, tuszmak commented
There's a merge conflict currently with DBInitializer. If we resolve that, it looks good!

2023-05-22 15:30 UTC, tuszmak approved these changes

2023-05-23 06:40 UTC, gerigol commented on src/frontend/src/api/upFetch.js
> + * @returns Proems
```suggestion
 * @returns Proems -> Promis
```

2023-05-23 06:46 UTC, tuszmak commented on src/frontend/src/api/upFetch.js
> + * @returns Proems
*Promise

2023-05-23 06:52 UTC, gerigol commented on src/frontend/src/pages/projects/AssignsPeople.js
> +
also check for error, for example:
```
if (error) return <h1>{error}</h1>;
```

2023-05-23 06:52 UTC, gerigol commented on src/frontend/src/pages/projects/AssignsPeople.js
> +  const { data, isPending } = useDownFetch(url);
```suggestion
  const { data, isPending, error } = useDownFetch(url);
```

2023-05-23 06:56 UTC, gerigol commented on src/frontend/src/pages/projects/ModifyUserAssigns.js
> +
check for error
```
if (error) return <h1>{error}</h1>;
```

2023-05-23 06:58 UTC, gerigol commented on src/frontend/src/pages/projects/Projects.js
> +  if (isPending) return <h1>Loading</h1>;
check for error:
```
if (error) return <h1>{error}</h1>;
```

2023-05-23 07:00 UTC, gerigol requested changes
Please correct that one typeo and consider error checking when useDownFetch used

2023-05-23 07:27 UTC, MateWagner commented on src/frontend/src/pages/projects/AssignsPeople.js
> +
We need to speak how we will handle error or page, message, or something else

2023-05-23 07:32 UTC, gerigol approved these changes

2023-05-23 07:33 UTC, merged